<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="wwwroot\" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Microsoft.Extensions.Logging.Log4Net\Microsoft.Extensions.Logging.Log4Net.csproj" />
  </ItemGroup>

</Project>
